# branch
execute_process(
    COMMAND git rev-parse --abbrev-ref HEAD
    OUTPUT_VARIABLE GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(GIT_BRANCH STREQUAL "HEAD")
    set(GIT_BRANCH "detached")
endif()

# commit
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# dirty?
execute_process(
    COMMAND git status
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(GIT_STATUS)
    set(GIT_DIRTY "true")
else()
    set(GIT_DIRTY "false")
endif()

# remote url (assume origin))
execute_process(
    COMMAND git remote get-url origin
    OUTPUT_VARIABLE GIT_REMOTE_URL
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT GIT_REMOTE_URL)
    set(GIT_REMOTE_URL "unknown")
endif()

# closest tag (human readable version)
execute_process(
    COMMAND git describe --tags --abbrev=0
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    RESULT_VARIABLE GIT_DESCRIBE_RESULT
    OUTPUT_VARIABLE GIT_TAG
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT GIT_DESCRIBE_RESULT EQUAL 0)
    set(GIT_TAG "?.?.?")
endif()

# output to cpp file
file(WRITE ${OUTPUT_FILE}
    "// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED BY gen-build-info.cmake.\n"
    "#include \"BuildInfo.h\"\n"
    "\n"
    "const std::string BuildInfo::c_sTargetSDKVersion = \"${ZHMMODSDK_VER}\";\n"
    "const std::string BuildInfo::c_sBuildTag = \"${GIT_TAG}\";\n"
    "const std::string BuildInfo::c_sRemoteUrl = \"${GIT_REMOTE_URL}\";\n"
    "const std::string BuildInfo::c_sBranch = \"${GIT_BRANCH}\";\n"
    "const std::string BuildInfo::c_sCommit = \"${GIT_COMMIT_HASH}\";\n"
    "const bool BuildInfo::c_bIsDirty = ${GIT_DIRTY};\n"
)

# log to build output
message(STATUS "Generated build info:")
message(STATUS "  Target SDK Version: ${ZHMMODSDK_VER}")
message(STATUS "  Build Tag:          ${GIT_TAG}")
message(STATUS "  Remote URL:         ${GIT_REMOTE_URL}")
message(STATUS "  Branch:             ${GIT_BRANCH}")
message(STATUS "  Commit:             ${GIT_COMMIT_HASH}")
message(STATUS "  Is Dirty?:          ${GIT_DIRTY}")
