# branch
execute_process(
    COMMAND git rev-parse --abbrev-ref HEAD
    OUTPUT_VARIABLE GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(GIT_BRANCH STREQUAL "HEAD")
    set(GIT_BRANCH "detached")
endif()

# commit
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# dirty?
execute_process(
    COMMAND git status
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(GIT_STATUS)
    set(GIT_DIRTY "true")
else()
    set(GIT_DIRTY "false")
endif()

# remote url (assume origin))
execute_process(
    COMMAND git remote get-url origin
    OUTPUT_VARIABLE GIT_REMOTE_URL
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT GIT_REMOTE_URL)
    set(GIT_REMOTE_URL "unknown")
endif()

# output to cpp file
file(WRITE ${OUTPUT_FILE}
    "// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED BY gen-build-info.cmake.\n"
    "#include \"BuildInfo.h\"\n"
    "\n"
    "const std::string BuildInfo::c_sRemoteUrl = \"${GIT_REMOTE_URL}\";\n"
    "const std::string BuildInfo::c_sBranch = \"${GIT_BRANCH}\";\n"
    "const std::string BuildInfo::c_sCommit = \"${GIT_COMMIT_HASH}\";\n"
    "const bool BuildInfo::c_bIsDirty = ${GIT_DIRTY};\n"
)
